version: '3.9'

services:
  raffle_car:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    command: python main.py
    depends_on:
      - db_raffle
    env_file:
      - .env
    volumes:
      - ./.:/app

  db_raffle:
    image: postgres:12-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresql_volume:
